name: test

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    types: [opened, synchronize]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: lcfetch

      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt install -y -q build-essential libreadline-dev libx11-dev libxrandr-dev

      - name: Build and run lcfetch
        run: |
          cd ./lcfetch
          make run
